# Copyright 2025 TRAPS

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: push-version-branches
description: Push major and minor branches

inputs:
  checkout:
    description: First decide whether to check or not
    required: false
    default: true
  token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  tag:
    description: Tag
    required: false
    default: ${GITHUB_REF#refs/*/}

runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ inputs.checkout }}
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Get versions
      id: get-versions
      run: |
        echo major=$(echo ${{ inputs.tag }} | cut -d. -f1) >> "$GITHUB_OUTPUT"
        echo minor=$(echo ${{ inputs.tag }} | cut -d. -f1-2) >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Push major branch
      run: |
        git checkout -B ${{ steps.get-versions.outputs.major }}
        git push origin ${{ steps.get-versions.outputs.major }}
      shell: bash

    - name: Push minor branch
      run: |
        git checkout -B ${{ steps.get-versions.outputs.minor }}
        git push origin ${{ steps.get-versions.outputs.minor }}
      shell: bash
