# Copyright 2024 TRAPS

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ros2-docker-build
description: Build Docker Image and push to ghcr.io

inputs:
  checkout:
    description: First decide whether to check or not
    required: false
    type: boolean
    default: true
  workspace-dir:
    description: ROS2 Workspace directory
    required: false
    default: ./ros2_ws
  platforms:
    description: Docker Image platform (comma separation)
    required: false
    default: linux/amd64, linux/arm64/v8
  rosdistro:
    description: ROS distribution (lowercase)
    required: false
    default: humble
  apt-requirements:
    description: Apts required for Docker Build
    required: false
  token:
    description: TOKEN used to push Docker Image
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  - name: Set repository name
    id: set-repository-name
    run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
    shell: bash

  - name: Checkout
    if: ${{ fromJson(inputs.checkout) }}
    uses: actions/checkout@v4
    with:
      path: ${{ inputs.workspace-dir }}/src/${{ steps.set-repository-name.outputs.name }}
  
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.token }}
      logout: false

  - name: Extract metadata (tags, labels) for Docker
    id: set-docker-metadata
    uses: docker/metadata-action@v5
    with:
      images: ghcr.io/${{ github.repository }}
  
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3
    with:
      platforms: ${{ inputs.platforms }}

  - name: Set up Docker Buildx
    id: set-docker-builder
    uses: docker/setup-buildx-action@v3
    with:
      platforms: ${{ inputs.platforms }}

  - name: Build and push
    uses: docker/build-push-action@v5
    with:
      context: /
      file: ${{ github.action_path }}/Dockerfile
      push: true
      tags: ${{ steps.set-docker-metadata.outputs.tags }}
      labels: ${{ steps.set-docker-metadata.outputs.labels }}
      build-args: |
        BASE_IMAGE=ros:${{ inputs.rosdistro }}-ros-base
        WORKSPACE_DIR=${{ github.workspace }}/${{ inputs.workspace-dir }}
        APT_REQUIREMENTS=${{ inputs.apt-requirements }}
        ENTRYPOINT_FILE=${{ github.action_path }}/ros_ws_entrypoint.sh
      no-cache: true
      platforms: ${{ inputs.platforms }}
      builder: ${{ steps.set-docker-builder.outputs.name }}