name: Colcon Test test

run-name: Colcon Test test:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

env:
  TARGET_ACTION: ${{ github.repository }}/colcon-test@${{ github.sha }}

jobs:
  colcon-test:
    runs-on: ubuntu-22.04

    permissions:
      packages: read

    container:
      image: ros:humble-ros-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: TRAPS-Robocup/traps_tools_ros
          path: src/traps_tools_ros
      
      - name: Colcon test
        uses: ${{ env.TARGET_ACTION }}
        with:
          checkout: false
