name: "Updated: Docker Build ROS2 Package"

run-name: "Updated: Docker Build ROS2 Package:${{ github.ref_name }}(${{ github.event.head_commit.message }})"

on:
  push:

jobs:
  test-docker-build-ros2-pkg-action:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./docker-build-ros2-pkg
