name: Push tag

run-name: Push tag:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:
    branches:
      - 'main'

jobs:
  push-tag:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push tag
        uses: ./push-tag
        with:
          checkout: false
