name: Push tag

run-name: Push tag:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

jobs:
  add-tag:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    steps:
      - name: Push tag
        uses: ./push-tag
        with:
          checkout: false
