name: Add tag

run-name: Colcon Test test:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

jobs:
  add-tag:
    runs-on: ubuntu-22.04

    permissions:
      packages: write

    steps:
      - name: Add tag
        uses: ./.traps-github-action/ros2-add-tag
