name: Docker Build

run-name: Docker Build:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read

    env:
      PLATFORMS: linux/amd64, linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .traps-github-action

      - name: Resist repository name
        id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: TRAPS-Robocup/traps_tools_ros
          path: ros2_ws/src/traps_tools_ros
      
      - name: Docker Build and Push
        uses: ./.traps-github-action/ros2-docker-build
        with:
          checkout: false
