name: Docker Build Test

run-name: Docker Build Test:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .traps-github-action

      - name: Checkout traps_example_ros
        uses: actions/checkout@v4
        with:
          path: ./ros2_ws/src/traps_example_ros
          repository: TRAPS-RoboCup/traps_example_ros

      - name: Build and push
        uses: ./.traps-github-action/ros2-docker-build@main
        with:
          checkout: false
          workspace-path: ./ros2_ws
          platforms: linux/amd64, linux/arm64/v8
          rosdistro: humble
          apt-requirements: